export default{
    "Employees":[
        {
            "empid":1,
            "name":"Raj",
            "band":"C1"
        },
        {
            "empid":2,
            "name":"Aakash",
            "band":"D1"
        },
        {
            "empid":3,
            "name":"Ananth",
            "band":"D1"
        },
        {
            "empid":4,
            "name":"Kiran",
            "band":"B1"
        },
        {
            "empid":5,
            "name":"Sai",
            "band":"B1"
        },
    ]
}